### ISSUE TITLE
example notebook

### ISSUE THREAD

**Issue by JimB99** [Lukas-Orion/NOrbit#2]
Clean up notebook. 
Functions are still defined separately instead of imported from NOrbit.function.
Not sure if we should explain every single function or just do an overall guide?

**Comment by Lukas-Orion** [comment]
Functions are now accessible from NOrbit and notebook shows two examples of solar system simulations, where it first explains the algorithm and N-body simulations. The notebook should be pretty intuitive and easy to follow!

**Comment by Lukas-Orion** [comment]
Functions are now accessible from NOrbit and notebook shows two examples of solar system simulations, where it first explains the algorithm and N-body simulations. The notebook should be pretty intuitive and easy to follow!
